# Author: Niko

# Special Location names for e.g. rooms are listed below:
# tester_activate (activation button), tester_room (checking room locations), tester_redstone (will be a redstone block), tester_reactionblocks (reaction blocks), tester_teleportback (teleport out), tester_teleportin (teleport in)
# generator_button (activation/disable button for generator)
# vent (vent spectate), vent_out (vent teleport location)
# trap_activation (activate button), trap_blocks (blocks to remove)

traitor:
  # Amount of traitors in the round.
  # Value will be multiplied with the players amount and will be the amount of traitors in the round
  amount: 0.38
  # the maximum amount of traitors in the round can be
  maximum: 4

detective:
  # Amount of detectives in the round.
  # Value will be multiplied with the players amount and will be the amount of detectives in the round
  amount: 0.15
  # the minimum amount of players, when detectives will be selected
  minimum: 4


# Determine the probability an item drop when clicking on a chest.
# To add an entry just type:
# MATERIAL:SUBID:PROBABILITY;
# and simply delete the entry or set the probability to 0 to
# remove the item.
#
# If you want to add an enchantment to the item type:
# MATERIAL:SUBID:PROBABILITY:ENCHANTMENT:LEVEL;
#
# If you want to add a potion to the item type:
# MATERIAL:SUBID:PROBABILITY:POTION:DURATION:LEVEL:RGB;
#
# The MATERIAL needs to be the exact spigot 1.12 MATERIAL name: https://aboodyy.net/spigot-api/javadocs/1.12.2/org/bukkit/Material.html
# The ENCHANTMENT needs to be the exact spigot 1.12 ENCHANTMENT name: https://aboodyy.net/spigot-api/javadocs/1.12.2/org/bukkit/enchantments/Enchantment.html
# The POTION needs to be the exact spigot 1.12 POTION name: https://aboodyy.net/spigot-api/javadocs/1.12.2/org/bukkit/potion/PotionType.html
# KNOCKBACK:1  ARROW_INFINITE:1   ARROW_KNOCKBACK:1    FIRE_ASPECT:1  PROTECTION_ENVIRONMENTAL:1  PROTECTION_ENVIRONMENTAL:2  PROTECTION_FIRE:1   PROTECTION_PROJECTILE:1   THORNS:2
chest:
  contents: 'STONE_SWORD:0:1:25;BOW:0:1:25;ARROW:0:32:25;WOODEN_SWORD:0:1:25'
  endercontents: 'IRON_SWORD:0:1:5.5;BOW:0:1:2.5:ARROW_DAMAGE:1'
